name: tours-and-travels CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3   # Latest version, compatible with Node.js 20

    - name: Set up Node.js
      uses: actions/setup-node@v3   # Latest version, compatible with Node.js 20
      with:
        node-version: '20.x'   # Explicitly specify Node.js 20

    - name: Install dependencies and build backend
      run: |
        cd backend
        npm install
        npm run build

    - name: Install dependencies and build frontend
      run: |
        cd frontend
        npm install
        npm run build
